// Setup Console STDOUT globals
GLOBAL HEADER_OFFSET to 5.
GLOBAL UI_HEADER_ROW to "+--------------+----------------------------+".
GLOBAL UI_FILLER_ROW to "|                                           |".

// EVENTS
GLOBAL EVENT_CTRL_SURFACE_LOCK_STATUS_CHANGE to "EVENT_CTRL_SURFACE_LOCK_STATUS_CHANGE".
GLOBAL EVENT_ROTOR_ANGLE_DELTA_STRENGTH_CHANGE to "EVENT_ROTOR_ANGLE_DELTA_STRENGTH_CHANGE".
GLOBAL EVENT_ROTOR_ANGLE_CHANGE TO "EVENT_ROTOR_ANGLE_CHANGE".
GLOBAL EVENT_ROTOR_LOCK_STATUS_CHANGE TO "EVENT_ROTOR_LOCK_STATUS_CHANGE".
GLOBAL EVENT_VTOL_CONTROLS_ENABLED_CHANGE TO "EVENT_VTOL_CONTROLS_ENABLED_CHANGE".

GLOBAL NUMBER_OF_ROTORS to LEX("value", 0).